version: '3.7'
services:
    postgres:
        container_name: db
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5433:5432'
        volumes: 
          - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_ADDRESS},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":${NFS_PATH-/volume1/docker/}${COMPOSE_PROJECT_NAME}/db_data"